version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

services:
  cleaner:
    <<: *base-dev
    image: salimfadhley/python_cleaner:latest
    build:
      context: .
      target: cleaner
    volumes:
      - ./src:/src
      - .:/project